### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by afshin2003** [shimaore/esl#32]
Hi Shimaore,
Happy new year :) 
I was wondering if you had this error before :
**warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.**
I am using node v0.10.40 + esl 4.0.1. In the attachment you can find the whole log trace.

Best,
Afshin

[esl-log.txt](https://github.com/shimaore/esl/files/77146/esl-log.txt)

**Comment by shimaore** [comment]
@afshin2003 Try `enqueue_api` instead of `api`. Or better use `bgapi` if that is OK for your application.
(The issue is that `api` is a synchronous operation on the socket, so you can't run multiple ones concurrently. In 5.0 `api` uses the `enqueue` mechanism by default so that detail is hidden.)

PS: `enqueue` is not in 4.0.1 though, but if your application serializes the calls to `api` that will do.

**Comment by afshin2003** [comment]
Stéphane,
It seems for me the right choice is using bgapi!

Cheers,
Afshin
